### ISSUE TITLE
Is there any animated-vector support?

### ISSUE THREAD

**Issue by Artman12** [devendroid/VectorChildFinder#15]
I get error trying to use this library with animated-vector.

Here's my animated-vector:

`
<animated-vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt">
    <aapt:attr name="android:drawable">
        <vector
            android:width="24dp"
            android:height="24dp"
            android:viewportWidth="24"
            android:viewportHeight="24">
            <path
                android:name="root"
                android:strokeWidth="2"
                android:strokeLineCap="square"
                android:fillColor="#000000"
                android:pathData="M4.8,13.4 L9,17.6 M10.4,16.2 L19.6,7" />
        </vector>
    </aapt:attr>
    <target android:name="root">
        <aapt:attr name="android:animation">
            <objectAnimator
                android:propertyName="pathData"
                android:valueFrom="M4.8,13.4 L9,17.6 M10.4,16.2 L19.6,7"
                android:valueTo="M6.4,6.4 L17.6,17.6 M6.4,17.6 L17.6,6.4"
                android:duration="300"
                android:interpolator="@android:interpolator/fast_out_slow_in"
                android:valueType="pathType" />
        </aapt:attr>
    </target>
</animated-vector>
`

Here's my code:

`       
        VectorChildFinder finder = new VectorChildFinder(getContext(), iconRes, icon);
        VectorDrawableCompat.VFullPath path = finder.findPathByName("root");
        Log.i("!!!!!!!!!!", "path: " + path);
        if (path != null) {
            path.setFillColor(Utils.getColorFromString(getContext(), device.getDeviceId()));
        }
`

Here's my logcat:

`2020-08-21 13:00:11.070 10360-10360/com.test.test E/VectorDrawableCompat: parser error
    org.xmlpull.v1.XmlPullParserException: Binary XML file line #2<vector> tag requires viewportWidth > 0
        at com.devs.vectorchildfinder.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:561)
        at com.devs.vectorchildfinder.VectorDrawableCompat.inflate(VectorDrawableCompat.java:494)
        at com.devs.vectorchildfinder.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:456)
        at com.devs.vectorchildfinder.VectorDrawableCompat.create(VectorDrawableCompat.java:437)
        at com.devs.vectorchildfinder.VectorChildFinder.<init>(VectorChildFinder.java:22)
        at com.test.test.views.MyCardView.setIcon(MyCardView.java:171)
        at com.test.test.views.MyCardView.prepareDevice(MyCardView.java:66)
        at com.test.test.views.MyCardView.updateUi(MyCardView.java:58)
        at com.test.test.presenters.MyPresenter.onBindViewHolder(MyPresenter.java:44)
        at com.test.test.presenters.MyPresenter.onBindViewHolder(MyPresenter.java:17)
        at com.test.test.presenters.AbstractCardPresenter.onBindViewHolder(AbstractCardPresenter.java:32)
        at androidx.leanback.widget.Presenter.onBindViewHolder(Presenter.java:140)
        at androidx.leanback.widget.ItemBridgeAdapter.onBindViewHolder(ItemBridgeAdapter.java:422)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7308)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6175)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6441)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6281)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6277)
        at androidx.leanback.widget.GridLayoutManager.measureScrapChild(GridLayoutManager.java:1302)
        at androidx.leanback.widget.GridLayoutManager.processRowSizeSecondary(GridLayoutManager.java:1386)
        at androidx.leanback.widget.GridLayoutManager.onMeasure(GridLayoutManager.java:1490)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3710)
        at android.view.View.measure(View.java:24552)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24552)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24552)
        at androidx.leanback.widget.GridLayoutManager.measureChild(GridLayoutManager.java:1582)
        at androidx.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1684)
        at androidx.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
        at androidx.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:389)
        at androidx.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1852)
        at androidx.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2282)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4277)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3980)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4546)
        at android.view.View.layout(View.java:21934)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at androidx.leanback.widget.ScaleFrameLayout.onLayout(ScaleFrameLayout.java:173)
        at android.view.View.layout(View.java:21934)
2020-08-21 13:00:11.074 10360-10360/com.test.test E/VectorDrawableCompat:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21934)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21934)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21934)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21934)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:21934)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
        at android.view.View.layout(View.java:21934)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3080)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2590)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by devendroid** [comment]
No, Current version of the library doesn't support animated-vector.
